services:
  whatsapp-api:
    image: ${REGISTRY}/${DOCKERHUB_USERNAME}/${IMAGE_NAME}:latest
    container_name: whatsapp-api
    restart: unless-stopped
    ports:
      - "3000:3000"  # Expose API port directly for nginx setup
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - TZ=UTC  # Set timezone for consistent log rotation
    networks:
      - whatsapp-network
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    mem_limit: 512m
    cpus: "0.5"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

networks:
  whatsapp-network:
    driver: bridge
