version: '3.8'

services:
  whatsmeow-bot:
    image: ${DOCKER_USERNAME:-yourusername}/whatsmeow-maiga:${TAG:-latest}
    container_name: whatsmeow-gin-bot
    ports:
      - "${API_PORT:-8080}:8080"
    volumes:
      - ${DATA_DIR:-./whatsmeow-data}:/app/data
    environment:
      - TZ=Asia/Jakarta
    restart: always
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  caddy:
    image: caddy:2
    container_name: caddy-proxy
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - caddy_logs:/var/log/caddy
    depends_on:
      - whatsmeow-bot
    restart: always
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "caddy", "version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  caddy_data:
  caddy_config:
  caddy_logs:

networks:
  app-network:
    driver: bridge