services:
  whatsapp-api:
    image: ${REGISTRY}/${DOCKERHUB_USERNAME}/${IMAGE_NAME}:latest
    container_name: whatsapp-api
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - whatsapp-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  caddy:
    build:
      context: .
      dockerfile: Dockerfile.caddy
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
      - ./logs:/var/log/caddy
    networks:
      - whatsapp-network
    depends_on:
      whatsapp-api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "caddy", "version"]
      interval: 10s
      timeout: 5s
      retries: 3
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

volumes:
  caddy_data:
  caddy_config:

networks:
  whatsapp-network:
    driver: bridge