name: Docker Build and Push

on:
  # Automatic triggers
  push:
    branches: [ "main", "nginx-local" ]
    paths:
      - 'main.go'
      - 'pkg/**'
      - 'internal/**'
      - 'Dockerfile'
      - 'docker-compose.yml'
      - 'supervisor.conf'
      - 'supervisord.yaml'
  pull_request:
    branches: [ "main", "nginx-local" ]
    paths:
      - 'main.go'
      - 'pkg/**'
      - 'internal/**'
      - 'Dockerfile'
      - 'docker-compose.yml'
      - 'supervisor.conf'
      - 'supervisord.yaml'
  # Schedule for regular builds
  schedule:
    - cron: '0 0 * * 0'  # Every Sunday at midnight UTC
  # Manual trigger
  workflow_dispatch:
    inputs:
      variant:
        description: 'Build variant'
        required: false
        default: 'latest'
        type: choice
        options:
          - 'latest'
          - 'main'
          - 'latest-nginx'
      tag:
        description: 'Custom tag for the Docker image (optional)'
        required: false
        default: ''
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Determine branch and checkout
        id: checkout
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            if [ "${{ github.event.inputs.variant }}" = "latest-nginx" ]; then
              echo "branch=nginx-local" >> $GITHUB_OUTPUT
              echo "target=latest-nginx" >> $GITHUB_OUTPUT
            elif [ "${{ github.event.inputs.variant }}" = "main" ]; then
              echo "branch=main" >> $GITHUB_OUTPUT
              echo "target=main" >> $GITHUB_OUTPUT
            else
              echo "branch=main" >> $GITHUB_OUTPUT
              echo "target=latest" >> $GITHUB_OUTPUT
            fi
          elif [ "${{ github.ref }}" = "refs/heads/nginx-local" ]; then
            echo "branch=nginx-local" >> $GITHUB_OUTPUT
            echo "target=latest-nginx" >> $GITHUB_OUTPUT
          else
            echo "branch=main" >> $GITHUB_OUTPUT
            echo "target=default" >> $GITHUB_OUTPUT
          fi

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.checkout.outputs.branch }}
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
          cache: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:latest
            network=host

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/bake-action@v4
        with:
          files: |
            ./docker-bake.hcl
          targets: ${{ steps.checkout.outputs.target }}
          push: true
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
