name: Docker Build and Push

on:
  # Automatic triggers
  push:
    branches: [ "main" ]
    paths:
      - 'main.go'
      - 'pkg/**'
      - 'internal/**'
      - 'Dockerfile'
      - 'docker-compose.yml'
      - 'supervisor.conf'
      - 'supervisord.yaml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'main.go'
      - 'pkg/**'
      - 'internal/**'
      - 'Dockerfile'
      - 'docker-compose.yml'
      - 'supervisor.conf'
      - 'supervisord.yaml'
  # Schedule for regular builds
  schedule:
    - cron: '0 0 * * 0'  # Every Sunday at midnight UTC
  # Manual trigger
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for the Docker image'
        required: false
        default: 'latest'
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
          cache: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:latest
            network=host

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Determine build target
        id: build-target
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            if [ "${{ github.event.inputs.tag }}" != "latest" ]; then
              echo "target=main" >> $GITHUB_OUTPUT
            else
              echo "target=latest" >> $GITHUB_OUTPUT
            fi
          else
            echo "target=default" >> $GITHUB_OUTPUT
          fi

      - name: Build and push Docker images
        uses: docker/bake-action@v6
        with:
          files: |
            ./docker-bake.hcl
          targets: ${{ steps.build-target.outputs.target }}
          push: true
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
