name: Update Go Dependencies

on:
  schedule:
    # Run every Sunday at midnight UTC
    - cron: '0 0 * * 0'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    # Update permissions to include necessary scopes
    permissions:
      contents: write
      pull-requests: write
      actions: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
          cache: true

      - name: Update dependencies
        run: |
          # Get current date for branch name and PR title
          DATE=$(date +"%Y-%m-%d") || exit 1
          
          # Create a new branch for the updates
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git checkout -b deps/update-$DATE || exit 1
          
          # Update all dependencies
          go get -u ./... || exit 1
          go mod tidy || exit 1
          
          # Check if there are any changes
          if git diff --exit-code go.mod go.sum; then
            echo "No dependency updates found"
            exit 0
          fi
          
          # Commit the changes
          git add go.mod go.sum || exit 1
          git commit -m "chore: update dependencies $DATE" || exit 1
          
          # Push the branch to the remote repository
          git push origin deps/update-$DATE || exit 1

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          # Changed from token to branch-token per v7 upgrade requirements
          branch-token: ${{ secrets.GH_TOKEN }}
          title: "chore: update Go dependencies"
          body: |
            This PR updates Go dependencies to their latest versions.
            
            This is an automated PR created by the weekly dependency update workflow.
            
            ## Changes
            - Updated Go dependencies to latest versions
            - Run `go mod tidy` to clean up dependencies
            
            ## Checks
            - [ ] Review the changes to ensure they don't introduce breaking changes
            - [ ] Run tests locally if needed
          branch: deps/update-$DATE
          base: main
          labels: |
            dependencies
            automated
          draft: false
          # New v7 options
          maintainer-can-modify: true
          delete-branch: true

      - name: Run tests
        run: go test ./... || exit 1

