on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      actions: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
          cache: true

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Update dependencies
        id: update
        run: |
          DATE=$(date +"%Y-%m-%d")
          BRANCH_NAME="deps/update-$DATE"
          echo "date=$DATE" >> $GITHUB_OUTPUT
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
          
          # Create and switch to a new branch
          git switch -c "$BRANCH_NAME"
          
          # Update all dependencies
          go get -u ./...
          go mod tidy
          
          # Check if there are any changes
          if git diff --quiet go.mod go.sum; then
            echo "No dependency updates found"
            echo "has_changes=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          # Stage and commit the changes
          git add go.mod go.sum
          git commit -m "chore: update dependencies $DATE"
          
          # Push the branch to the remote repository
          git push --set-upstream origin "$BRANCH_NAME"
          echo "has_changes=true" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: steps.update.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GH_TOKEN }}
          branch: ${{ steps.update.outputs.branch_name }}
          base: main
          title: "chore: update Go dependencies"
          body: |
            This PR updates Go dependencies to their latest versions.
            This is an automated PR created by the weekly dependency update workflow.
          labels: dependencies, automated
          draft: false
          maintainer-can-modify: true
          delete-branch: true

      - name: Run tests
        if: steps.update.outputs.has_changes == 'true'
        run: go test ./... || exit 1
